#!/usr/bin/env bash
# A Bash script that runs an infinite loop and handles SIGTERM gracefully

# Trap SIGTERM and print OK when received
trap 'echo "OK"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done
